%% 
% amri_nifti_def() - definitions specified in NIFTI format
%
% Usage
%  NIFTIDEF = amri_nifti_def;
%
% Version:
%   1.00
%
% Reference:
%   http://nifti.nimh.nih.gov/nifti-1

%% History
% 1.00 - 04/06/2010 - ZMLIU - Create the file

function NIFTIDEF = amri_nifti_def


NIFTIDEF.DT.NONE            = 0;
NIFTIDEF.DT.UNKNOWN         = 0;
NIFTIDEF.DT.BINARY          = 1;
NIFTIDEF.DT.UNSIGNED_CHAR   = 2;
NIFTIDEF.DT.SIGNED_SHORT    = 4;
NIFTIDEF.DT.SIGNED_INT      = 8;
NIFTIDEF.DT.FLOAT           = 16;
NIFTIDEF.DT.COMPLEX         = 32;
NIFTIDEF.DT.DOUBLE          = 64;
NIFTIDEF.DT.RGB             = 128;
NIFTIDEF.DT.ALL             = 255;
NIFTIDEF.DT.UINT8           = 2;
NIFTIDEF.DT.INT16           = 4;
NIFTIDEF.DT.INT32           = 8;
NIFTIDEF.DT.FLOAT32         = 16;
NIFTIDEF.DT.COMPLEX64       = 32;
NIFTIDEF.DT.FLOAT64         = 64;
NIFTIDEF.DT.RGB24           = 128;
NIFTIDEF.DT.INT8            = 256;
NIFTIDEF.DT.UINT16          = 512;
NIFTIDEF.DT.UINT32          = 768;
NIFTIDEF.DT.INT64           = 1024;
NIFTIDEF.DT.UINT64          = 1280;
NIFTIDEF.DT.FLOAT128        = 1536;
NIFTIDEF.DT.COMPLEX128      = 1792;
NIFTIDEF.DT.COMPLEX256      = 2048;
NIFTIDEF.DT.RGBA32          = 2304;

NIFTIDEF.INTENT.CORREL      = 2;        
NIFTIDEF.INTENT.TTEST       = 3;        
NIFTIDEF.INTENT.FTEST       = 4;        
NIFTIDEF.INTENT.ZSCORE      = 5;        
NIFTIDEF.INTENT.CHISQ       = 6;        
NIFTIDEF.INTENT.BETA        = 7;        
NIFTIDEF.INTENT.BINOM       = 8;        
NIFTIDEF.INTENT.GAMMA       = 9;        
NIFTIDEF.INTENT.POISSON     = 10;       
NIFTIDEF.INTENT.NORMAL      = 11;       
NIFTIDEF.INTENT.FTEST_NONC  = 12;       
NIFTIDEF.INTENT.CHISQ_NONC  = 13;       
NIFTIDEF.INTENT.LOGISTIC    = 14;       
NIFTIDEF.INTENT.LAPLACE     = 15;       
NIFTIDEF.INTENT.UNIFORM     = 16;       
NIFTIDEF.INTENT.TTEST_NONC  = 17;       
NIFTIDEF.INTENT.WEIBULL     = 18;       
NIFTIDEF.INTENT.CHI         = 19;       
NIFTIDEF.INTENT.INVGAUSS    = 20;
NIFTIDEF.INTENT.EXTVAL      = 21;
NIFTIDEF.INTENT.PVAL        = 22;
NIFTIDEF.INTENT.LOGPVAL     = 23;
NIFTIDEF.INTENT.LOG10PVAL   = 24;
NIFTIDEF.INTENT.FIRST_STATCODE = 2;
NIFTIDEF.INTENT.LAST_STATCODE  = 24;

NIFTIDEF.INTENT.ESTIMATE    = 1001;
NIFTIDEF.INTENT.LABEL       = 1002;
NIFTIDEF.INTENT.NEURONAME   = 1003;
NIFTIDEF.INTENT.GENMATRIX   = 1004;
NIFTIDEF.INTENT.SYMMATRIX   = 1005;
NIFTIDEF.INTENT.DISPVECT    = 1006;
NIFTIDEF.INTENT.VECTOR      = 1007;
NIFTIDEF.INTENT.POINTSET    = 1008;
NIFTIDEF.INTENT.TRIANGLE    = 1009;
NIFTIDEF.INTENT.QUATERNION  = 1010;
NIFTIDEF.INTENT.DIMLESS     = 1011;
NIFTIDEF.INTENT.TIME_SERIES = 2001;
NIFTIDEF.INTENT.NODE_INDEX  = 2002;
NIFTIDEF.INTENT.RGB_VECTOR  = 2003;
NIFTIDEF.INTENT.RGBA_VECTOR = 2004;
NIFTIDEF.INTENT.SHAPE       = 2005;

NIFTIDEF.XFORM.UNKNOWN      = 0;
NIFTIDEF.XFORM.SCANNER_ANAT = 1;
NIFTIDEF.XFORM.ALIGNED_ANAT = 2;
NIFTIDEF.XFORM.TALAIRACH    = 3;
NIFTIDEF.XFORM.MNI_152      = 4;

return;
